server:
  port: 8088
  servlet:
    context-path: "/"
logging:
  level:
    org:
      springframework: fatal
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?allowMultiQueries=true
    username: root
    password: '*23#dpffla511'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
mybatis:
  type-aliases-package: com.example.restfulwebservice.user
  mapper-locations: classpath:mapper/*.xml
